### ISSUE TITLE
reupload to a new hosting location

### ISSUE THREAD

**Issue by cooljeanius** [Dugy/contextfree_generator#1]
So, previously the CFG Generator was hosted at this link: https://www.physics.muni.cz/~dugi/index.fcgi/cfggen
However, now the link currently fails, with the following error message:
```
Forbidden

You don't have permission to access this resource.
Apache/2.4.54 (Debian) mod_fcgid/2.3.9 OpenSSL/1.1.1n mod_wsgi/4.7.1 Python/3.9 Server at www.physics.muni.cz Port 443
```
Reuploading somewhere else would be helpful.

**Comment by Dugy** [comment]
It's here: https://dugy.github.io/?M2NvbvRmdWzsbGFu5zJzb3VyY+V0eXDlf21haW49e0hlbGxvfSwge3Zpc2l0b3J9IQpIZWxsbz1IZWxsb3xIZXl8V2VsY29tZQp2aXNpdG9yPXZpc2l0b3J8ZnJpZW5kfHBhbABjY2ZnAkA=

Where did you find that old link? I would like to update it.

**Comment by cooljeanius** [comment]
> It's here: [dugy.github.io/?M2NvbvRmdWzsbGFu5zJzb3VyY+V0eXDlf21haW49e0hlbGxvfSwge3Zpc2l0b3J9IQpIZWxsbz1IZWxsb3xIZXl8V2VsY29tZQp2aXNpdG9yPXZpc2l0b3J8ZnJpZW5kfHBhbABjY2ZnAkA=](https://dugy.github.io/?M2NvbvRmdWzsbGFu5zJzb3VyY+V0eXDlf21haW49e0hlbGxvfSwge3Zpc2l0b3J9IQpIZWxsbz1IZWxsb3xIZXl8V2VsY29tZQp2aXNpdG9yPXZpc2l0b3J8ZnJpZW5kfHBhbABjY2ZnAkA=)
> 
> Where did you find that old link? I would like to update it.

on the Wesnoth forums: https://forums.wesnoth.org/viewtopic.php?t=43792

**Comment by Dugy** [comment]
Okay, I have updated the link in the OP.
